# Generated by Django 5.0.6 on 2024-06-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_proyecto_ticket_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='descripcion',
            field=models.TextField(max_length=200, verbose_name='descipcion'),
        ),
    ]
