# Generated by Django 5.0.6 on 2024-06-10 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_bien', models.CharField(max_length=50, verbose_name='Código Bien')),
                ('codigo_anterior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Anterior')),
                ('codigo_provisional', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Provisional')),
                ('codigo_nuevo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Nuevo')),
                ('nombre_bien', models.CharField(max_length=100, verbose_name='Nombre Bien')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serie')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('material', models.CharField(max_length=50, verbose_name='Material')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('custodio_actual', models.CharField(max_length=150, verbose_name='Custodio Actual')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Archivo Adjunto')),
                ('estado_registro', models.BooleanField(default=True, verbose_name='Estado de Registro')),
            ],
        ),
        migrations.CreateModel(
            name='CambioCustodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevo_custodio', models.CharField(max_length=150, verbose_name='Nuevo Custodio')),
                ('cedula_nuevo_custodio', models.CharField(max_length=20, verbose_name='Cédula Nuevo Custodio')),
                ('fecha_cambio', models.DateField(verbose_name='Fecha de Cambio')),
                ('modelo_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mymodel')),
            ],
        ),
    ]
