# Generated by Django 5.0.6 on 2024-08-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DireccionIp', models.CharField(blank=True, max_length=200, null=True, verbose_name='DireccionIp')),
                ('Usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('Contrasena', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contrasena')),
                ('Servicio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Servicio')),
                ('Puerto', models.CharField(blank=True, max_length=25, null=True, verbose_name='Puerto')),
                ('RutaImportante', models.CharField(blank=True, max_length=100, null=True, verbose_name='RutaImportante')),
                ('UbicacionFisica', models.CharField(blank=True, max_length=250, null=True, verbose_name='UbicacionFisica')),
                ('NumeroSerie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serie/Modelo')),
            ],
        ),
    ]
