# Generated by Django 5.0.6 on 2024-08-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'permissions': [('view_custom_mymodel', 'Can view MyModel'), ('edit_custom_mymodel', 'Can edit MyModel'), ('remove_custom_mymodel', 'Can remove MyModel')]},
        ),
    ]
