# Generated by Django 5.0.6 on 2024-08-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mymodel_descripcionprocesos_mymodel_entorno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='DireccionIp',
            new_name='DireccionIpLocal',
        ),
    ]
