# Generated by Django 5.0.6 on 2024-08-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_direccionip_mymodel_direccioniplocal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='DireccionIpLocal',
            new_name='DireccionIp',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='DescripcionProcesos',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='Entorno',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='Marca',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='Modelo',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='NombreServidor',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='SistemaOperativo',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='direccionIpPublica',
        ),
    ]
