# Generated by Django 5.0.6 on 2024-08-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_direccioniplocal_mymodel_direccionip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApisYsubdominios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion')),
                ('Ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ip')),
                ('puerto', models.CharField(blank=True, max_length=50, null=True, verbose_name='puerto')),
                ('NombreServicioHttps', models.CharField(blank=True, max_length=100, null=True, verbose_name='NombreServicioHttps')),
            ],
        ),
        migrations.CreateModel(
            name='Subdominios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('IpPublica', models.CharField(blank=True, max_length=100, null=True, verbose_name='IpPublica')),
                ('IpInterna', models.CharField(blank=True, max_length=100, null=True, verbose_name='IpInterna')),
                ('Host', models.CharField(blank=True, max_length=100, null=True, verbose_name='Host')),
            ],
            options={
                'permissions': [('view_custom_mymodel', 'Can view MyModel'), ('edit_custom_mymodel', 'Can edit MyModel'), ('remove_custom_mymodel', 'Can remove MyModel')],
            },
        ),
        migrations.AlterModelOptions(
            name='mymodel',
            options={},
        ),
    ]
