# Generated by Django 5.0.6 on 2024-08-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_apisysubdominios_subdominios_alter_mymodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreServidor', models.CharField(blank=True, max_length=50, null=True, verbose_name='NombreServidor')),
                ('Ubicacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicacion')),
                ('Marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('Modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('NumeroSerie', models.CharField(blank=True, max_length=25, null=True, verbose_name='NumeroSerie')),
                ('SistemaOperativo', models.CharField(blank=True, max_length=50, null=True, verbose_name='SistemaOperativo')),
                ('PuertoRelevante', models.CharField(blank=True, max_length=50, null=True, verbose_name='PuertoRelevante')),
                ('Entorno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Entorno')),
                ('Estado', models.BooleanField(blank=True, max_length=15, null=True, verbose_name='Estado')),
                ('DireccionIpLocal', models.CharField(blank=True, max_length=50, null=True, verbose_name='DireccionIpLocal')),
                ('DireccionIpPublica', models.CharField(blank=True, max_length=50, null=True, verbose_name='DireccionIpPublica')),
                ('Usuario', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuario')),
                ('Clave', models.CharField(blank=True, max_length=25, null=True, verbose_name='Clave')),
                ('DescripcionProcesos', models.CharField(blank=True, max_length=100, null=True, verbose_name='DescripcionProcesos')),
            ],
            options={
                'permissions': [('view_custom_mymodel', 'Can view MyModel'), ('edit_custom_mymodel', 'Can edit MyModel'), ('remove_custom_mymodel', 'Can remove MyModel')],
            },
        ),
        migrations.CreateModel(
            name='Nodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Host', models.CharField(blank=True, max_length=100, null=True, verbose_name='Host')),
                ('Usuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario')),
                ('Ram', models.CharField(blank=True, max_length=25, null=True, verbose_name='Ram')),
                ('Disco', models.CharField(blank=True, max_length=25, null=True, verbose_name='Disco')),
                ('SistemaOperativo', models.CharField(blank=True, max_length=50, null=True, verbose_name='SkistemaOperativo')),
                ('Descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion')),
                ('Contrasena', models.CharField(blank=True, max_length=50, null=True, verbose_name='contrasena')),
            ],
        ),
        migrations.AlterModelOptions(
            name='subdominios',
            options={},
        ),
    ]
