# Generated by Django 5.0.6 on 2024-08-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_formulario_nodos_alter_subdominios_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Servidores',
        ),
    ]
