# Generated by Django 5.0.6 on 2024-08-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_mymodel_servidores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisysubdominios',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='apisysubdominios',
            name='Ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='apisysubdominios',
            name='NombreServicioHttps',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Servicio HTTPS'),
        ),
        migrations.AlterField(
            model_name='apisysubdominios',
            name='puerto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puerto'),
        ),
    ]
